### ISSUE TITLE
Dots overlap meaning on cannot be clicked on.

### ISSUE THREAD

**Issue by powerc9000** [townhallproject/mutual-aid-networks#22]
On a mobile view you don't get a listing of groups as on desktop.

So you can't see every group in an area if the points are stacked. In Salt lake city there are two networks right on top of one another. Only one of them can ever be selected and a mobile user would never know the other existed. Should bump the longitude slightly for either of the Salt Lake City Utah ones so they are not right on top of one another.

**Comment by meganrm** [comment]
Done
