### ISSUE TITLE
Display languages available on Mutual Aid card

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/mutual-aid-networks#37]
Currently languages are listed in Column J, separated by commas. Let us know if we should change format.

https://docs.google.com/spreadsheets/d/1X7E_XqBs7Pdlb7KDUG8g4jkDY3lfHj4AJV0LRYF2VQE/edit#gid=0

**Comment by meganrm** [comment]
some of them are '/' separated and some are ',' separated. It doesn't matter for adding them, i'm just displaying whats in the text box, but it will matter if we want to use it as a filter

**Comment by nathanmwilliams** [comment]
Is there a preference for the future filter? I assume comma?
