### ISSUE TITLE
color points by their 'category' field

### ISSUE THREAD

**Issue by meganrm** [townhallproject/mutual-aid-networks#6]

**Comment by bguggs** [comment]
I don't have access to contribute and have to go for tonight, but this can be done by replacing the 'color-circle' line in the addLayer method with the following:

```
'circle-color': [
    'match',
    ['get', 'category'],
    'General',
    '#fbb03b',
    /* other */ '#11b4da'
]
```
I wasn't sure what all of the categories are but they can just be added like the 'General' category.

See: https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/ for more info
