### ISSUE TITLE
Add "Share your story" banner

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/mutual-aid-networks#99]
COPY

Expanded Unemployment Benefits expire on July 31. If you -- or a loved one -- is depending in this support to make rent, mortgage, and other essentials, help us lift up your story to lawmakers. **[SHARE YOUR STORY TODAY.]**(https://twitter.com/GoddardRiv/status/1278757777511518211)

**Comment by meganrm** [comment]
is this still something I should do?

**Comment by nathanmwilliams** [comment]
Ah, no. This was a summer thing. I'll close.
